General:
  RetroMode:
    Enabled: true
  Locale: en_US
Abilities:
  Enabled: true
  Messages: true
  Activation:
    Only_Activate_When_Sneaking: false
  Cooldowns:
    Blast_Mining: 60
    Super_Breaker: 240
  Max_Seconds:
    Blast_Mining: 0
    Super_Breaker: 0
  Tools:
    Durability_Loss: 1
Skills:
  Mining:
    Level_Cap: 0
    Detonator_Name: FLINT_AND_STEEL
Bonus_Drops:
  Mining:
    Tuff: true
    Deepslate_Redstone_Ore: true
    Deepslate_Copper_Ore: true
    Deepslate_Coal_Ore: true
    Deepslate_Diamond_Ore: true
    Deepslate_Emerald_Ore: true
    Deepslate_Iron_Ore: true
    Deepslate_Gold_Ore: true
    Deepslate_Lapis_Ore: true
    Lapis_Lazuli_Ore: true
    Copper_Ore: true
    Calcite: true
    Smooth_Basalt: true
    Block_Of_Amethyst: true
    Budding_Amethyst: true
    Small_Amethyst_Bud: true
    Medium_Amethyst_Bud: true
    Large_Amethyst_Bud: true
    Amethyst_Cluster: true
    Amethyst_Shard: true
    Deepslate: true
    Cobbled_Deepslate: true
    Gilded_Blackstone: true
    Crying_Obsidian: true
    Nether_Bricks: true
    Red_Nether_Bricks: true
    Cracked_Nether_Bricks: true
    Chiseled_Nether_Bricks: true
    Chain: true
    Blackstone: true
    Basalt: true
    Polished_Basalt: true
    Nether_Gold_Ore: true
    Warped_Nylium: true
    Crimson_Nylium: true
    Ancient_Debris: true
    Netherite_Scrap: true
    Andesite: true
    Diorite: true
    Granite: true
    Coal_Ore: true
    Coal: true
    Diamond_Ore: true
    Diamond: true
    Emerald_Ore: true
    Emerald: true
    End_Stone: true
    Glowstone: true
    Glowstone_Dust: true
    Gold_Ore: true
    Gold_Nugget: true
    Iron_Ore: true
    Iron_Ingot: true
    Lapis_Ore: true
    Lapis_Lazuli: true
    Mossy_Cobblestone: true
    Netherrack: true
    Obsidian: true
    Nether_Quartz_Ore: true
    Quartz: true
    Redstone_Ore: true
    Redstone: true
    Redstone_Dust: true
    Sandstone: true
    Stone: true
    Cobblestone: true
    Raw_Copper: true
    Raw_Iron: true
    Raw_Gold: true
